"""empty message

Revision ID: 61646d4afac9
Revises: 
Create Date: 2021-07-06 14:29:40.826371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61646d4afac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=150), nullable=True),
    sa.Column('is_veggie', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
